Bilal/validate all links for EU, ROW and DIEL
deriv-com/e2e-deriv-com pull request #114
Opened 2024-02-05 11:16 UTC by bilalmajid-deriv

Refactored logic for checkAllLinks.cy.js to create test for validateAllLinks.cy.js and complete the test. added recursive function for checkLink to traverse through all the links available on homepage as well as all the child pages which fall in the scope of Deriv.com. Adding Checking function to check for certain conditions as well before validating a link and to make sure the recursive function is not stuck in a loop.

The test takes a total time of approximately 7-10 minutes and validates all possible links and child links 
Added comments for each Function created 
two urls which are added in excluded visit and check links are to be removed after fix is provided for them.
Will remove the previous test file wip/checkAllLinks.cy.js once this is approved/merged.

2024-02-05 16:55 UTC, markodonnell-deriv requested changes
Looks good. Could you put the Clickup Test Case code in the describe?

2024-02-06 02:59 UTC, bilalmajid-deriv commented
The Clickup Test ID has been added to describe. Thanks

2024-02-06 04:32 UTC, bilalmajid-deriv commented
@markodonnell-deriv I have also added a check to verify if the visited page is not showing 404 page not found.

2024-02-06 11:59 UTC, markodonnell-deriv requested changes

2024-02-06 11:59 UTC, markodonnell-deriv commented on cypress/e2e/full/validateAllLinks.cy.js
> +describe('QATEST-96657 - Check URL in deriv.com', () => {
I'm not seeing 96657 in the test case bank. Is this the squad task id?

2024-02-06 15:09 UTC, markodonnell-deriv approved these changes

2024-02-06 15:09 UTC, merged