homebannerupdate
deriv-com/e2e-deriv-com pull request #131
Opened 2024-02-22 10:50 UTC by infanta-deriv

This PR has update of script for homebanner to include awards check and Trust Pilot
Card - https://app.clickup.com/t/20696747/DERC-2466

2024-02-23 10:30 UTC, markodonnell-deriv requested changes
Indentation needed

2024-02-23 10:30 UTC, markodonnell-deriv commented on cypress/e2e/smoke/allHomeBanner.cy.js
> +    cy.findByRole('img', { name: 'Best forex spreads APAC 2023 by UF Awards' }).should('be.visible')
Indentation needed

2024-02-23 10:30 UTC, markodonnell-deriv commented on cypress/e2e/smoke/allHomeBanner.cy.js
> +    cy.findByRole('img', { name: 'Best forex spreads APAC 2023 by UF Awards' }).should('not.exist')
Indentation needed

2024-02-26 12:45 UTC, markodonnell-deriv approved these changes
Looks good

2024-02-28 02:07 UTC, meeyun-deriv approved these changes
LGTM

2024-02-28 02:07 UTC, merged