pricingscriptupdate
deriv-com/e2e-deriv-com pull request #134
Opened 2024-02-26 14:02 UTC by infanta-deriv

This PR has code for including new market in pricing check for both EU and Non EU
Card - https://app.clickup.com/t/20696747/DERC-2467 ,

2024-02-26 14:16 UTC, markodonnell-deriv approved these changes
Looks good.

2024-02-27 11:33 UTC, bilalmajid-deriv commented on cypress/support/livepricing.js
> +  cy.findAllByText('ETFs').eq(0).should('be.visible')
@infanta-deriv Isn't this assertion a little vague as it will be getting the first element having the text ETFs in the complete page and I see there is a total of 6 elements having test ETFs in them
<img width="1552" alt="Screenshot 2024-02-27 at 19 25 19" src="https://github.com/deriv-com/e2e-deriv-com/assets/155507124/484e27e1-19e8-470b-908c-e37906cd40b2">

And as the test is to verify all instruments for particular market is displayed should we not be asserting if all the instruments are visible one by one 
for example:  creating an array of all the instruments that should be available and asserting if those are available

2024-02-28 06:17 UTC, infanta-deriv commented on cypress/support/livepricing.js
> +  cy.findAllByText('ETFs').eq(0).should('be.visible')
sure @bilalmajid-deriv will make this change

2024-02-29 03:23 UTC, bilalmajid-deriv requested changes
@infanta-deriv the test logic seems much better now, but I see there are multiple code duplications. 
I have highlighted some of the duplications could you please take a look into all of all the duplications  in your changes and create parameterized functions/commands for all the duplications. Thanks

2024-02-29 03:23 UTC, bilalmajid-deriv commented on cypress/support/livepricing.js
> +  })
Can you create a cypress command or a function  to deal with the code duplication

2024-02-29 03:23 UTC, bilalmajid-deriv commented on cypress/support/livepricing.js
> +
Can we introduce a parameterized function or command here to deal with the duplication of code

2024-02-29 06:44 UTC, bilalmajid-deriv approved these changes
LGTM

2024-03-01 03:38 UTC, merged