paymentmethod-smoke
deriv-com/e2e-deriv-com pull request #153
Opened 2024-03-12 10:11 UTC by infanta-deriv

Card - https://app.clickup.com/t/20696747/DPROD-3812 , https://app.clickup.com/t/20696747/DPROD-3813 
This PR has script for homepage - Payment methods for ROW and EU

2024-03-12 18:20 UTC, rajendra-deriv approved these changes
Looks good to me

2024-03-13 05:19 UTC, meeyun-deriv requested changes

2024-03-13 05:19 UTC, meeyun-deriv commented on cypress/e2e/smoke/allHomePayments.cy.js
>  describe('Validate payment methods section in home page', () => {
can you also help to add the test case custom ID?

2024-03-13 07:33 UTC, markodonnell-deriv approved these changes
Looks good

2024-03-13 07:40 UTC, meeyun-deriv approved these changes
LGTM

2024-03-13 07:40 UTC, merged