Added Contact Us page
deriv-com/e2e-deriv-com pull request #172
Opened 2024-03-29 09:03 UTC by pardis-deriv

# Summary
Create Cypress test QATEST-1651 - About Us - Contact Us

# Ticket
https://app.clickup.com/t/20696747/DPROD-3782

<img width="512" alt="Screenshot 2024-03-29 at 4 54 07 PM" src="https://github.com/deriv-com/e2e-deriv-com/assets/142371916/58ab2009-1c9d-4747-84d7-55047012e27e">

2024-04-01 02:28 UTC, meeyun-deriv approved these changes
LGTM

2024-04-05 03:58 UTC, bilalmajid-deriv approved these changes

2024-05-28 03:55 UTC, bilalmajid-deriv requested changes
can you please add respective tags

2024-05-28 03:55 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsContactUs.cy.js
> +    it('should validate Contact Us page for EU', () => {
```suggestion
    it('should validate Contact Us page for EU', {tags: ['@full-tests', '@eu-tests']}, () => {
```

2024-05-28 03:55 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsContactUs.cy.js
> +    it('should validate Contact Us page for ROW', () => {
```suggestion
    it('should validate Contact Us page for ROW', {tags: ['@full-tests', '@row-tests']}, () => {
```

2024-05-28 03:55 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsContactUs.cy.js
> +    it('should validate Contact Us page for EU', () => {
```suggestion
    it('should validate Contact Us page for EU', {tags: ['@full-tests', '@eu-tests']}, () => {
```

2024-05-28 03:55 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsContactUs.cy.js
> +    it('should validate Contact Us page for ROW', () => {
```suggestion
    it('should validate Contact Us page for ROW', {tags: ['@full-tests', '@row-tests']}, () => {
```

2024-06-14 08:07 UTC, closed without merging