Hasan/updated deriv-com's urls
deriv-com/e2e-deriv-com pull request #173
Opened 2024-03-29 10:19 UTC by hasan-deriv

2024-03-29 10:32 UTC, habib-deriv approved these changes

2024-04-01 02:29 UTC, bilalmajid-deriv requested changes
hi @hasan-deriv this will not work as you will have to update all the test files as well which are using the env variables because in the code these env vars are used to append the base url with the region 

Apart from this the tests are triggered in Github by passing the baseUrl as input and the tests will still fail kindly update in the .yml as well

2024-04-01 02:59 UTC, meeyun-deriv requested changes
`derivAppUrl` is still using `https://staging-app.deriv.com`.

You can try to trigger the smoke test from your PR by selecting your branch from the github action workflow. So that we can make sure the PR has fully fixed the smoke tests.

2024-04-01 02:59 UTC, meeyun-deriv commented on cypress.config.js
> +    RegionEU: 'https://staging.eu-deriv-com-pages.pages.dev',
since some of the existing tests are appending the baseURL with query `?region=mt` and `?region=id` to switch to EU and ROW content, we need to handle those tests to be able to accept this full EU and ROW URL changes.

2024-04-02 09:45 UTC, maliheh-deriv commented on cypress/support/location.js
> +     * `_location-layout__Iframe-sc-n7n0xj-12` is dynamically created className. It's not reliable as selector. We could use data-cy here.
please create a card for this query in board and remove the commented line.

2024-04-02 09:47 UTC, maliheh-deriv commented on cypress/support/POM/expectedURLs.js
> +        // 'https://appgallery.huawei.com/app/C103801913',
can we add this justification as reference 
## enable this line if checking cypress/e2e/full/comparelinksROW.cy.js locally.

2024-04-02 09:51 UTC, maliheh-deriv commented on cypress/e2e/smoke/rowFooter.cy.js
> +    // cy.get(`a[href*="${appGallery}"]`)
please add proper justification like https://github.com/deriv-com/e2e-deriv-com/pull/173/files#r1547519278.

2024-04-02 09:52 UTC, maliheh-deriv commented on cypress/e2e/smoke/euHomeHamburger.cy.js
> -//Remove this test for now, as the Vercel Url doesn't support it.
@bilalmajid-deriv can you confirm if this part of code can be removed or not.

2024-04-02 09:57 UTC, maliheh-deriv commented on cypress/e2e/smoke/allHomeHeader.cy.js
> +    cy.c_waitForPageLoad()
This wait can be removed.

2024-04-02 09:58 UTC, maliheh-deriv commented on cypress/e2e/full/tradingPlatformMT5.cy.js
> +    // TODO: `.carousel-style__StyledChevron-sc-1wwuyp8-5.carousel-style__ChevronRight-sc-1wwuyp8-8.kDISbi.jVDjEi` need to be changed
please help to create a card in board and remove the commented lines.

2024-04-02 10:00 UTC, maliheh-deriv commented on cypress/e2e/full/tradingPlatformDerivX.cy.js
> +        cy.c_waitForPageLoad()
This wait can be removed.

2024-04-02 10:00 UTC, maliheh-deriv commented on cypress/e2e/full/tradingPlatformDbot.cy.js
> +        cy.c_waitForPageLoad()
This wait can be removed

2024-04-02 10:02 UTC, maliheh-deriv commented on cypress/e2e/full/comparelinksROW.cy.js
> +  cy.clearAllCookies()
This line can be removed.

2024-04-02 10:02 UTC, maliheh-deriv commented on cypress/e2e/full/careersHomepage.cy.js
> +        cy.c_waitForPageLoad()
This wait can be removed.

2024-04-02 10:02 UTC, maliheh-deriv commented on cypress/e2e/full/careersHomepage.cy.js
> +        cy.c_waitForPageLoad()
This wait can be removed.

2024-04-02 10:05 UTC, maliheh-deriv commented on cypress/e2e/full/allLocationPage.cy.js
> +      //  cy.c_checkMap()
please add justification and mention the card to fix the issue.

2024-04-02 10:06 UTC, maliheh-deriv commented on cypress/e2e/full/careersHomepage.cy.js
> +        // TODO: `.carousel-style__ChevronRight-sc-1wwuyp8-8` selector also need to be chnaged
please add the card in board and remove the commented lines.

2024-04-03 02:27 UTC, maliheh-deriv commented on cypress.config.js
>      RegionDIEL: '/?region=za',
based on new changes, "RegionDIEL" also need to be updated in the code.

2024-04-03 02:52 UTC, hasan-deriv commented on cypress/e2e/full/careersHomepage.cy.js
> +        // TODO: `.carousel-style__ChevronRight-sc-1wwuyp8-8` selector also need to be chnaged
removed

2024-04-03 02:53 UTC, hasan-deriv commented on cypress/e2e/full/careersHomepage.cy.js
> +        cy.c_waitForPageLoad()
removed

2024-04-03 02:53 UTC, hasan-deriv commented on cypress/e2e/full/careersHomepage.cy.js
> +        cy.c_waitForPageLoad()
removed

2024-04-03 02:54 UTC, hasan-deriv commented on cypress/e2e/full/comparelinksROW.cy.js
> +  cy.clearAllCookies()
removed

2024-04-03 02:54 UTC, hasan-deriv commented on cypress/e2e/full/tradingPlatformDbot.cy.js
> +        cy.c_waitForPageLoad()
removed

2024-04-03 02:57 UTC, hasan-deriv commented on cypress/e2e/full/tradingPlatformDerivX.cy.js
> +        cy.c_waitForPageLoad()
removed

2024-04-03 02:57 UTC, hasan-deriv commented on cypress/e2e/full/tradingPlatformMT5.cy.js
> +    // TODO: `.carousel-style__StyledChevron-sc-1wwuyp8-5.carousel-style__ChevronRight-sc-1wwuyp8-8.kDISbi.jVDjEi` need to be changed
removed

2024-04-03 02:59 UTC, hasan-deriv commented on cypress/e2e/smoke/allHomeHeader.cy.js
> +    cy.c_waitForPageLoad()
removed

2024-04-03 03:03 UTC, hasan-deriv commented on cypress/e2e/smoke/euHomeHamburger.cy.js
> -//Remove this test for now, as the Vercel Url doesn't support it.
I added it back

2024-04-03 03:19 UTC, hasan-deriv commented on cypress/support/location.js
> +     * `_location-layout__Iframe-sc-n7n0xj-12` is dynamically created className. It's not reliable as selector. We could use data-cy here.
removed

2024-04-03 03:27 UTC, bilalmajid-deriv commented on cypress/support/e2e.js
>  Cypress.Commands.add("c_visitResponsive", (path, size, quickLoad ) => {
Instead of using the waitForPageLoad here after every visit why nt make it part of the c_visitResponsive command
and pass an optional parameter such as withWait which when ever set to true will wait for the whatsapp icon else it wont
something like this 

`Cypress.Commands.add("c_visitResponsive", (path, size, quickLoad , options={}) => {
  const{
    waitLoad = false
  } = options
  //Custom command that allows us to use baseUrl + path and detect with this is a responsive run or not.
  cy.log(path);
  if (size === undefined) size = Cypress.env("viewPortSize");

  if (size == "small") cy.viewport("iphone-xr");
  else if (size == "medium") cy.viewport("ipad-2");
  else if (size == "desktop") cy.viewport("macbook-16");

  cy.visit(path);
  if (quickLoad === undefined){
  if (waitLoad == true) {
    //Wait for relevent elements to appear (based on page)
    cy.log("Home page Selected");
    cy.c_waitForPageLoad() //For the home page, this seems to be the best indicator that a page has fully loaded. It may change in the future.
  }`

2024-04-03 08:39 UTC, bilalmajid-deriv approved these changes

2024-04-03 09:09 UTC, maliheh-deriv commented on cypress/e2e/full/allLocationPage.cy.js
> +      //  cy.c_checkMap()
https://deriv-group.slack.com/archives/C04FCKXMS8Y/p1712135179922879?thread_ts=1712122218.498689&cid=C04FCKXMS8Y

2024-04-03 09:13 UTC, maliheh-deriv commented on cypress/e2e/smoke/rowFooter.cy.js
> +    // cy.get(`a[href*="${appGallery}"]`)
for Row footer , if the appGallery is going to be visible again we can keep the code, else please remove this part as appGallery is not visible in staging and production.

2024-04-03 09:34 UTC, maliheh-deriv commented on cypress/e2e/smoke/rowFooter.cy.js
> +    // cy.get(`a[href*="${appGallery}"]`)
will check appGallery later , to remove the tag from block status .

2024-04-03 09:35 UTC, maliheh-deriv commented
LGTM

2024-04-03 10:16 UTC, meeyun-deriv approved these changes
LGTM

2024-04-03 10:16 UTC, merged