mayuran/DPROD-3499/smoke-testfix
deriv-com/e2e-deriv-com pull request #176
Opened 2024-04-03 11:18 UTC by mayuran-deriv

2024-04-03 14:39 UTC, markodonnell-deriv requested changes

2024-04-03 14:39 UTC, markodonnell-deriv commented on cypress/e2e/smoke/euHomeHamburger.cy.js
> +    cy.get('[data-testid="warning-pop-up"]').then(($warningPopUp) => $warningPopUp.length > 0 && cy.get('[data-testid="warning-pop-up"] [alt="Close"]').click())
Use testing library friendly elements where possible.
If you install the Playwright locator generator (in a separate folder!) it will usually find one for you.
See docs: https://wikijs.deriv.cloud/en/Quality-Assurance/e2e-test-automation 
and reach out in #need_help_cypress if necessary.

2024-04-04 07:58 UTC, abuzar-deriv commented on cypress/e2e/smoke/euHomeHamburger.cy.js
> +    cy.findByTestId("warning-pop-up").then(($warningPopUp) => $warningPopUp.length > 0 && cy.findByTestId("warning-pop-up-close-button").click())
Can you try just with cy.findByTestId("warning-pop-up-close-button").click()? Reason being if warning-pop-up is not present, test will stop there anyway.

2024-04-04 08:15 UTC, mayuran-deriv commented on cypress/e2e/smoke/euHomeHamburger.cy.js
> +    cy.findByTestId("warning-pop-up").then(($warningPopUp) => $warningPopUp.length > 0 && cy.findByTestId("warning-pop-up-close-button").click())
first we have to check the pop up is exist or not
so thats why i added a check for pop up

2024-04-04 08:38 UTC, abuzar-deriv commented on cypress/e2e/smoke/euHomeHamburger.cy.js
> +    cy.findByTestId("warning-pop-up").then(($warningPopUp) => $warningPopUp.length > 0 && cy.findByTestId("warning-pop-up-close-button").click())
Cypress tests fail as soon as they can't locate the element. Basically it will only move to then once it finds "warning-pop-up". If it can't it will fail there itself, throwing error that it couldn't find 'warning-pop-up'.

2024-04-04 08:45 UTC, abuzar-deriv commented on cypress/e2e/smoke/euHomeHamburger.cy.js
> +    cy.findByTestId("warning-pop-up").then(($warningPopUp) => $warningPopUp.length > 0 && cy.findByTestId("warning-pop-up-close-button").click())
You will have to try something like:
`cy.document().then((doc) => {
    const popup = doc.querySelector('[data-test-id="warning-pop-up"]')
    if (popup) {
      cy.findByTestId("warning-pop-up-close-button").click()
    }
  })`

2024-04-04 09:21 UTC, abuzar-deriv approved these changes
LGTM

2024-04-04 09:26 UTC, aswathy-deriv approved these changes

2024-04-04 10:20 UTC, markodonnell-deriv approved these changes
Looks good

2024-04-04 10:58 UTC, merged