Check on platform row
deriv-com/e2e-deriv-com pull request #178
Opened 2024-04-04 10:43 UTC by shenbakavanee-deriv

In this test case we will be checking the platforms under [User-friendly trading platforms] in Deriv.com homepage and check the image & descriptions for ROW region.

Card: https://app.clickup.com/t/20696747/DPROD-3900

2024-04-05 03:12 UTC, abuzar-deriv requested changes
Looks fine in general but can you please replace all instances of `cy.get` with cypress testing library commands? You may use playwright code gen to find the locators.

2024-04-05 03:12 UTC, abuzar-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.get('#platformtab-trigger-1').click();
Please use:
```suggestion
        cy.findByRole('tab', { name: 'CFDs' })
```

2024-04-05 03:12 UTC, abuzar-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.get('img[alt="deriv mt5"]').should('be.visible').click();
Please use:
```suggestion
        cy.findByRole('img', { name: 'deriv mt5' })
```

2024-04-05 03:12 UTC, abuzar-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.get('img[alt="Deriv MT5"]').first().click();
Can you please use cypress testing library commands?

2024-04-05 03:12 UTC, abuzar-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.get('img[alt="deriv ctrader"]').should('be.visible').click();
Same here

2024-04-05 03:12 UTC, abuzar-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.get('img[alt="deriv x"]').should('be.visible').click();
Same

2024-04-05 03:12 UTC, abuzar-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.get('img[alt="Deriv X"]').first().click();
Here as well

2024-04-05 03:53 UTC, meeyun-deriv requested changes

2024-04-05 03:53 UTC, meeyun-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.c_visitResponsive('', {size:'desktop'})
please include mobile test as well

2024-04-05 03:53 UTC, meeyun-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.get('#platformtab-trigger-1').click();
i believe this is clicking `Trade` from the header. If so, you can try this instead
```
homeBanner.elements.tradeMenu().click()
```

2024-04-05 03:53 UTC, meeyun-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.get('img[alt="deriv mt5"]').should('be.visible').click();
```
cy.findAllByText('Deriv MT5').eq(0).should('be.visible').click()
```

can use this instead

2024-04-05 03:53 UTC, meeyun-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.get('img[alt="Deriv MT5"]').first().click();
do use testing library queries for all. If it is not possible due to the current code, we need to raise a card for FE developer to update that instead

2024-04-05 03:53 UTC, meeyun-deriv commented on cypress/e2e/wip/platform-row.cy.js
> +        cy.findByRole('link', { name: 'deriv logo label' }).click();
for the validation step, we should use `....should('something')...` instead of an action

2024-04-09 06:18 UTC, meeyun-deriv requested changes
move this test from `wip` folder to `full` folder

2024-04-09 06:36 UTC, meeyun-deriv approved these changes
LGTM

2024-04-09 06:37 UTC, merged