add regression workflow
deriv-com/e2e-deriv-com pull request #184
Opened 2024-04-08 05:09 UTC by maliheh-deriv

# Description 
combine smoke and full tests together to help manual team members during regression. 

# cards 
https://app.clickup.com/t/20696747/DPROD-4039

2024-04-22 06:19 UTC, bilalmajid-deriv approved these changes
LGTM

2024-04-22 12:11 UTC, markodonnell-deriv approved these changes
Looks good.

2024-04-23 05:26 UTC, meeyun-deriv requested changes

2024-04-23 05:26 UTC, meeyun-deriv commented on .github/workflows/cypress_cloud_manual.yml
> +        uses: actions/checkout@v4
please update to hash instead

2024-04-23 05:26 UTC, meeyun-deriv commented on .github/workflows/cypress_cloud_manual.yml
> +        uses: actions/checkout@v4
same for this

2024-04-23 05:26 UTC, meeyun-deriv commented on .github/workflows/cypress_cloud_manual.yml
> +          #   npx cypress run --spec cypress/e2e/smoke/*.js --record --parallel --key ${{ secrets.CYPRESS_MANUAL_RECORD_KEY }}
if the commented lines are not needed, we can remove this

2024-04-23 05:26 UTC, meeyun-deriv commented on .github/workflows/cypress_cloud_manual.yml
> +           repository: deriv-com/e2e-deriv-com # Replace with your repository name
please check the comments in the workflow and remove those unnecessary ones, e.g. for this one, i think it is not useful

2024-04-23 05:26 UTC, meeyun-deriv commented on .github/workflows/cypress_cloud_manual.yml
> +    if: ${{ github.event.inputs.suite == 'regression' || always() }}
Why do we need `always()` here as it will always being triggered regardless of the input options. E.g. smoke option is trigger for regression job as well:
![Uploading image.png…]()

2024-04-23 05:33 UTC, maliheh-deriv commented on .github/workflows/cypress_cloud_manual.yml
> +    if: ${{ github.event.inputs.suite == 'regression' || always() }}
The always() added to enable the workflow to trigger smoke and full jobs even if Full_extended failed.

2024-04-23 09:16 UTC, meeyun-deriv approved these changes
LGTM

2024-04-23 09:17 UTC, merged