percy fix snpashot name
deriv-com/e2e-deriv-com pull request #208
Opened 2024-04-22 08:56 UTC by indulekha-deriv

There were some discrepancy in percy identifying change due to difference in snapshot names from different URL's. This PR is to fix it.

2024-04-24 05:24 UTC, meeyun-deriv requested changes

2024-04-24 05:24 UTC, meeyun-deriv commented on .github/workflows/webflow_percy.yml
> +    - name: Install scroll-to-bottomjs plugin
can you please check why do we need this as we have included this in the `package.json`

Try to remove this part and trigger your test to see if the test needs this.

2024-04-24 20:52 UTC, indulekha-deriv commented on .github/workflows/webflow_percy.yml
> +    - name: Install scroll-to-bottomjs plugin
Removed from workflow and added only in  package.json. 
Workflow: https://github.com/deriv-com/e2e-deriv-com/actions/runs/8823137909

2024-04-25 07:44 UTC, meeyun-deriv approved these changes
LGTM

2024-04-25 07:44 UTC, merged