Safra/regulatory information eu
deriv-com/e2e-deriv-com pull request #215
Opened 2024-05-13 07:05 UTC by safra-deriv

Card: https://app.clickup.com/t/20696747/DPROD-3903

Description: To check on the EU Regulatory Information page on deriv.com

2024-05-13 07:22 UTC, bilalmajid-deriv reviewed
Left some comments

2024-05-13 07:22 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsRegulatoryInformation.cy.js
> +    //cy.go('back')
If not needed can remove the comments

2024-05-13 07:22 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsRegulatoryInformation.cy.js
> +    cy.go('back')
Add an assertion on visibility of an element on the next page for all as well before going back because cypress updates the url before redirecting completely to the new page hence resulting in false positives

2024-05-13 07:22 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsRegulatoryInformation.cy.js
> +    //cy.get('div').contains('67.28% of retail investor accounts')
please remove commented code if not needed

2024-05-13 07:22 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsRegulatoryInformation.cy.js
> +    //cy.findByRole('link').invoke("removeAttr", "target").click()
please remove commented out code if not needed

2024-05-13 07:22 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsRegulatoryInformation.cy.js
> +import { findByRole } from '@testing-library/dom'
can  you try without this as well because findByRole is imported in `import '@testing-library/cypress/add-commands'`
```suggestion

```

2024-05-13 07:22 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsRegulatoryInformation.cy.js
> +    //cy.go('back')
remove commented out code

2024-05-13 07:22 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsRegulatoryInformation.cy.js
> +
remove commented line of code if not needed

2024-05-13 07:22 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsRegulatoryInformation.cy.js
> +    it('should validate Regulatory Information page for EU', () => {
```suggestion
    it('should validate Regulatory Information page for EU', { tags: ['@full-tests', '@eu-tests'] }, () => {
```

2024-05-13 07:22 UTC, bilalmajid-deriv commented on cypress/e2e/full/aboutUsRegulatoryInformation.cy.js
> +    it('should validate Regulatory Information page for EU', () => {
```suggestion
    it('should validate Regulatory Information page for EU', { tags: ['@full-tests', '@eu-tests'] }, () => {
```

2024-05-14 08:23 UTC, meeyun-deriv requested changes
The current implementation on EU behaviour is outdated. We are no longer using `.../?region=at` to get EU page behaviour. So the implementation  
```
 cy.c_visitResponsive(`/regulatory/${Cypress.env('RegionEU')}`, 'desktop')
 ```
will not work as it will means visiting URL `/regulatory/https://staging.eu-deriv-com-pages.pages.dev` - which is an invalid URL.

Please update your branch with the latest master and edit the steps accordingly.

2024-05-23 02:46 UTC, bilalmajid-deriv approved these changes
LGTM

2024-05-23 02:46 UTC, merged