Updatesignuptest
deriv-com/e2e-deriv-com pull request #224
Opened 2024-06-14 14:06 UTC by infanta-deriv

card - https://app.clickup.com/t/20696747/DPROD-4004
This PR has script for the updated test case  QATEST 1378

2024-06-17 09:50 UTC, markodonnell-deriv requested changes

2024-06-17 09:50 UTC, markodonnell-deriv commented on cypress/e2e/smoke/allSignUps.cy.js
> +      cy.c_visitResponsive('/', { waitLoad: true, size: 'desktop' })
Unless I've missed something that was added to c_visitResponsive in recent weeks. waitLoad doesn't do anything.
And if you wanted to pass it as a parameter, it would probably belong to options, as we already have path, and size. So the syntax would be something like this: 
cy.c_visitResponsive('/', 'desktop', { waitLoad: true });

Depending on which page you're calling we will need to identify the last element to be displayed and check visibility on it.
Maybe we can have a call to discuss?

2024-06-19 08:32 UTC, infanta-deriv commented on cypress/e2e/smoke/allSignUps.cy.js
> +      cy.c_visitResponsive('/', { waitLoad: true, size: 'desktop' })
sure @markodonnell-deriv can have a call to discuss on this

2024-06-19 15:07 UTC, markodonnell-deriv commented on cypress/e2e/smoke/allSignUps.cy.js
> +      cy.c_visitResponsive('/', { waitLoad: true, size: 'desktop' })
Hi @infanta-deriv , as discussed, I misread the code. So I believe this should be fine.

2024-06-20 03:41 UTC, meeyun-deriv approved these changes
LGTM

2024-06-20 03:41 UTC, merged