renamed-common class name
deriv-com/e2e-deriv-com pull request #68
Opened 2023-11-24 01:55 UTC by mahnoorgul-deriv

In this PR, I have renamed commonEuPage's class. From `FooterEu` to `commonPage`.  As this class not only contains footer elements, but all other elements have been added in it.

2023-11-24 03:11 UTC, meeyun-deriv requested changes

2023-11-24 03:11 UTC, meeyun-deriv commented on cypress/support/POM/commonPage.js
> +    EulicencePdf: '/regulatory/Deriv_Investments_(Europe)_Limited.pdf',
lets standardised the camel case, it should be `euLicencePdf`

2023-11-24 03:18 UTC, mahnoorgul-deriv commented on cypress/support/POM/commonPage.js
> +    EulicencePdf: '/regulatory/Deriv_Investments_(Europe)_Limited.pdf',
updated in recent PR.

2023-11-24 08:44 UTC, markodonnell-deriv approved these changes
Looks good

2023-12-15 02:13 UTC, mahnoorgul-deriv commented
Reviewed this PR, closing it for now as some changes are already made to code no need to merge this.

2023-12-15 02:13 UTC, closed without merging