Mahn/check all links
deriv-com/e2e-deriv-com pull request #80
Opened 2023-12-15 06:51 UTC by mahnoorgul-deriv

This is the initial PR for Task https://app.clickup.com/t/20696747/DERC-2255.
Work in progress!

2023-12-20 09:24 UTC, mahnoorgul-deriv commented
this PR is ready for review

2023-12-22 07:40 UTC, meeyun-deriv requested changes

2023-12-22 07:40 UTC, meeyun-deriv commented on cypress/e2e/full/checkAllLinks.cy.js
> +  it('visit all captured urls, and capture their child links', () => {
this test is dependent on the first test, why are we separating them as 2 tests?
you can add a function to capture the link in the page, then reuse it in the later part of the code

2023-12-22 07:40 UTC, meeyun-deriv commented on cypress/e2e/full/checkAllLinks.cy.js
> +            failOnStatusCode: false,
the child link is not visited. Can we also try to visit the childlink and see how long it will take?

2023-12-22 07:40 UTC, meeyun-deriv commented on cypress/e2e/full/checkAllLinks.cy.js
> +        if (childUrl.includes('deriv.com') && !capturedUrls.includes(childUrl)) {
please take a look

2023-12-28 09:11 UTC, meeyun-deriv requested changes

2023-12-28 09:11 UTC, meeyun-deriv commented on cypress/e2e/full/checkAllLinks.cy.js
> +            cy.visit(url);
please help to remove `;` to follow the same coding style

2024-01-02 10:04 UTC, meeyun-deriv approved these changes
LGTM

2024-01-03 03:34 UTC, meeyun-deriv approved these changes
LGTM

2024-01-03 03:34 UTC, merged