add full coverage
deriv-com/e2e-deriv-com pull request #82
Opened 2023-12-18 08:41 UTC by pravin-deriv

I have added coverage for below testcase 
- https://app.clickup.com/t/20696747/DERC-2243
- https://app.clickup.com/t/20696747/QATEST-1298

Initially the coverages are wasnt sufficient, hence created a new PR for this.

2023-12-18 10:20 UTC, markodonnell-deriv requested changes

2023-12-18 10:20 UTC, markodonnell-deriv commented on cypress/e2e/smoke/allHomeHeader.cy.js
> +    cy.findByRole('link', {name: 'Multipliers trade type Multipliers Get the upside of CFDs without the downside of losing more than your stake.',}).should('be.visible')
There's lots of instances where theres's an extraneous comma after the name parameter. Styling should be consistent and more like line 21

2023-12-19 18:29 UTC, pravin-deriv commented
> There's lot's of duplication of test code in the I liked the original idea of having the single function in a loop and then you could pass the region as a parameter and do conditional statements where tests were unique to eu or row.

I made the fix @markodonnell-deriv

2023-12-19 18:30 UTC, pravin-deriv commented on cypress/e2e/smoke/allHomeHeader.cy.js
> +    cy.findByRole('link', {name: 'Multipliers trade type Multipliers Get the upside of CFDs without the downside of losing more than your stake.',}).should('be.visible')
I hope i did the changes, if not please do address me again 🙇

2023-12-28 09:20 UTC, meeyun-deriv requested changes
This PR will also need to update since the current staging has major changes

2023-12-28 09:20 UTC, meeyun-deriv commented on cypress/e2e/smoke/allHomeHeader.cy.js
> +            cy.findByRole('link', { name: 'Options trade type Options Earn a range of payouts without risking more than your initial stake.' }).should('be.visible')
we don't have to check the exact wording in all pages, because this should be able to detect from percy test. We can make sure the main menu item are listed there without verifying their description

2023-12-28 09:20 UTC, meeyun-deriv commented on cypress/e2e/smoke/allHomeHeader.cy.js
> +        check_market_menu('EU')
we also need to make sure the ROW only content is not appear in EU

2023-12-28 09:20 UTC, meeyun-deriv commented on cypress/e2e/smoke/allHomeHeader.cy.js
> +        cy.findByRole('button', { name: 'Log in' }).should('be.visible')
This login button can be included as `check_homepage_header` check

2023-12-28 09:26 UTC, pravin-deriv commented on cypress/e2e/smoke/allHomeHeader.cy.js
> +            cy.findByRole('link', { name: 'Options trade type Options Earn a range of payouts without risking more than your initial stake.' }).should('be.visible')
In the previous implement when we target trade types, its come with the description. I believe after new changes we can just check on the trade types without description.

2023-12-28 09:26 UTC, pravin-deriv commented on cypress/e2e/smoke/allHomeHeader.cy.js
> +        check_market_menu('EU')
Sure will add @meeyun-deriv

2024-01-03 02:15 UTC, meeyun-deriv approved these changes
LGTM

2024-01-03 17:00 UTC, markodonnell-deriv approved these changes
Looks good

2024-01-03 17:00 UTC, merged