Pravin/fix flaky test
deriv-com/e2e-deriv-com pull request #95
Opened 2024-01-08 03:22 UTC by pravin-deriv

Added scrollintoView() function and add a one-second wait time to avoid flaky issue.

2024-01-08 16:09 UTC, markodonnell-deriv requested changes
The inline comments might need a discussion and/or screen share :)

2024-01-08 16:09 UTC, markodonnell-deriv commented on cypress/e2e/smoke/allHomeTradeType.cy.js
> +    cy.findByRole('heading', { name: trade.name }).scrollIntoView().wait(1000) .should('exist')
Can we try and look for another way of achieving this? An enforced delay of a constant 1 sec is.
Do we need to checks for visible at all? Can we not just go to the click() and do a force if necessary.

2024-01-11 06:34 UTC, pravin-deriv commented on cypress/e2e/smoke/allHomeTradeType.cy.js
> +    cy.findByRole('heading', { name: trade.name }).scrollIntoView().wait(1000) .should('exist')
Hi @markodonnell-deriv , I have made the necessary changes to the code. Currently, I have not created any classes, arrays, or constants. I have taken a straightforward approach in writing the code to avoid any potential flaky test issues with unreliable testing. Please let me know if this works for you.

2024-01-11 06:34 UTC, pravin-deriv commented on cypress/e2e/smoke/allHomeTradeType.cy.js
> +    cy.findByRole('heading', { name: trade.name }).scrollIntoView().wait(1000) .should('exist')
https://cloud.cypress.io/projects/16kef2/runs/1611/overview?roarHideRunsWithDiffGroupsAndTags=1

2024-02-09 09:51 UTC, closed without merging