Signup test
deriv-com/e2e-deriv-com pull request #96
Opened 2024-01-10 10:37 UTC by markodonnell-deriv

Minor mods to the process, such as ensuring that the correct email link got chosen and the endpoint was set correctly.

2024-01-22 03:44 UTC, meeyun-deriv requested changes

2024-01-22 03:44 UTC, meeyun-deriv commented on cypress/support/e2e.js
> +    cy.get('a[href*="CustomerIO_account_opening_new.html"]').last().click()
searching for keyword `account_opening_new` should be sufficient. As sometimes it will show `Rudderstack` instead of `CustomerIO`

2024-01-22 03:44 UTC, meeyun-deriv commented on cypress/e2e/smoke/signUpCompleteFlow.cy.js
> +        //Disabled for now -- tradingPreference() // stuck at this point where we are not able to perform click on options from model
we had removed the AB testing from the site, so this part is not needed anymore

2024-01-22 03:44 UTC, meeyun-deriv commented on cypress/e2e/smoke/signUpCompleteFlow.cy.js
> +        cy.log('verification code' + verification_code)
do we need this log?

2024-01-22 03:44 UTC, meeyun-deriv commented on cypress/e2e/smoke/signUpCompleteFlow.cy.js
> +        cy.c_visitResponsive(Cypress.env("derivAppUrl") + '/endpoint', "desktop")
instead of manually setting the endpoint in `../endpoint` page, we can also setup faster by using the local storage, e.g:

```    
cy.c_visitResponsive(
      `https://app.deriv.com/`,
      "large"
    ).then(() => {
      cy.window().then((win) => {
        win.localStorage.setItem("config.server_url", Cypress.env('configServer'))
        win.localStorage.setItem("config.app_id", Cypress.env('configAppId'))
      })
    })
```

2024-01-22 03:44 UTC, meeyun-deriv commented on cypress/e2e/smoke/signUpCompleteFlow.cy.js
>          const signupUrl = `${Cypress.env("derivAppUrl")}/redirect?action=signup&lang=EN_US&code=${verification_code}&date_first_contact=${today.toISOString().split('T')[0]}&signup_device=desktop`
although this is not part of the PR changes, I think we should not hardcode the sign up verification URL. The URL parameter could change from the FE changes. If the URL is broken, we will not be able to detect the failure from our cypress test.

But I'm open if we want to improve this in current or new PR :)

2024-01-23 12:41 UTC, markodonnell-deriv commented on cypress/e2e/smoke/signUpCompleteFlow.cy.js
> +        cy.log('verification code' + verification_code)
Probably not, will remove.

2024-01-24 02:36 UTC, meeyun-deriv requested changes

2024-01-24 02:36 UTC, meeyun-deriv commented on cypress/e2e/smoke/signUpCompleteFlow.cy.js
> +      cy.c_visitResponsive("/endpoint","large")
the default deriv app URL will be able to set endpoint through local storage, so we don't have to go to endpoint page.

2024-01-24 02:36 UTC, meeyun-deriv commented on cypress/e2e/smoke/signUpCompleteFlow.cy.js
> +      cy.log('Server' + Cypress.env("configServer"))
i think we don't have to log this

2024-01-24 02:36 UTC, meeyun-deriv commented on cypress/e2e/smoke/signUpCompleteFlow.cy.js
> +        cy.log('verification code' + verification_code)
lets remove this then :)

2024-01-24 02:36 UTC, meeyun-deriv commented on cypress/e2e/smoke/signUpCompleteFlow.cy.js
> +      cy.wait(5000) //TODO - To be replaced by a loop within the emailVerification below.
do we have a card to handle this TODO item?

2024-01-30 06:44 UTC, meeyun-deriv approved these changes
LGTM

2024-01-30 07:15 UTC, merged