Fixed Smoke test failure
deriv-com/e2e-deriv-com pull request #99
Opened 2024-01-17 07:39 UTC by pravin-deriv

In this PR
- I have moved euHomeHamburger.cy.js to smoke folder
- I have fixed few of the test scripts that failed due to recent revamp

2024-01-17 18:12 UTC, markodonnell-deriv requested changes
Looks good with 1 minor comment.
Good use of force: true, by the way. It often comes in handy!

2024-01-17 18:12 UTC, markodonnell-deriv commented on cypress.config.js
> +    // baseUrl: 'https://deriv.com',
Best to remove comments. I think staging-app.deriv.com is a reasonable url to commit.

2024-01-18 09:35 UTC, habib-deriv commented on cypress.config.js
> +    // baseUrl: 'https://deriv.com',
```suggestion
```

2024-01-18 09:36 UTC, habib-deriv approved these changes
LGTM

2024-01-18 09:36 UTC, habib-deriv commented on cypress.config.js
> +    // baseUrl: 'https://deriv.com',
```suggestion
```

2024-01-18 09:40 UTC, markodonnell-deriv approved these changes
Looks good.

2024-01-18 09:41 UTC, markodonnell-deriv approved these changes
Looks good.

2024-01-18 09:41 UTC, markodonnell-deriv commented on cypress.config.js
>      //baseUrl: 'https://deriv-com-v2.pages.dev/',
Remove comment

2024-01-18 09:44 UTC, merged